services:
  mysql:
    image: mysql:8
    container_name: nest-mysql
    restart: always
    ports:
      - '3307:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./deploy/sql/:/docker-entrypoint-initdb.d
    env_file:
      - .env.prod
    networks:
      - my-net
  nest-admin-ts:
    image: nest-admin-image
    container_name: nest-admin-ts
    restart: always
    env_file:
      - .env
    ports:
      - '3000:${SERVER_PORT}'
    depends_on:
      - mysql
networks:
  my-net:
    name: my-net
